name: Deploy to Server

on:
  push:
    branches:
      - master  # Trigger this workflow on push to the master branch

jobs:
  deploy:
    runs-on: self-hosted  # This will use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository's code

      - name: Install dependencies
        run: npm install  # Install Node.js dependencies

      - name: Build project
        run: npm run build  # Build the project

      - name: Deploy and Restart Agent Service
        run: |
          echo "Deployment started..."
          # Pull the latest changes and build the project
          git pull origin master
          npm install
          npm run build
          # Restart the agent service
          sudo systemctl restart agent.service
          echo "Agent service restarted!"












# name: Deploy to Server via SSH

# on:
#   push:
#     branches:
#       - master  # Trigger this workflow on push to the main branch

# jobs:
#   deploy:
#     runs-on: self-hosted  # Use your self-hosted runner (instead of ubuntu-latest)

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2  # Checkout your repository's code

#       - name: Install dependencies
#         run: npm install  # Install Node.js dependencies

#       - name: Build project
#         run: npm run build  # Build the project

#       - name: Restart with PM2
#         run: pm2 restart 0  # Restart your app with PM2 (adjust if needed)


   

      
        

      # - name: Set up SSH private key
      #   uses: appleboy/ssh-action@master  # Use Appleboy's SSH Action
      #   with:
      #     host: ${{ secrets.HOST }}  # Server's IP address or hostname
      #     username: ${{ secrets.USERNAME }}  # SSH username (e.g., ubuntu for AWS EC2)
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}  # The private SSH key secret
      #     port: 22  # SSH port (default is 22)
      #     script: |
      #           ls
      #           cd Frontend
      #           ls
      #           git pull
      #           npm i
      #           npm run build 
      #           pm2 restart 0
            # Commands to run on your remote server
            #cd /path/to/your/project  # Navigate to your project directory
            #git pull origin main  # Pull the latest changes from GitHub
            #npm install  # Install project dependencies
            #npm run build  # Build your project (or your custom build script)
            #sudo systemctl restart nginx  # Restart nginx or other services
